return
{
  entities =
  {
    {"stone-wall", {x = -8.5, y = -4.5}, {}},
    {"stone-wall", {x = -6.5, y = -4.5}, {}},
    {"stone-wall", {x = -7.5, y = -4.5}, {}},
    {"stone-wall", {x = -4.5, y = -4.5}, {}},
    {"stone-wall", {x = -5.5, y = -4.5}, {}},
    {"stone-wall", {x = -2.5, y = -4.5}, {}},
    {"stone-wall", {x = -0.5, y = -4.5}, {}},
    {"stone-wall", {x = -1.5, y = -4.5}, {}},
    {"stone-wall", {x = 1.5, y = -4.5}, {}},
    {"stone-wall", {x = 3.5, y = -4.5}, {}},
    {"stone-wall", {x = 2.5, y = -4.5}, {}},
    {"stone-wall", {x = 5.5, y = -4.5}, {}},
    {"stone-wall", {x = 6.5, y = -4.5}, {}},
    {"stone-wall", {x = 7.5, y = -4.5}, {}},
    {"stone-wall", {x = 8.5, y = -4.5}, {}},
    {"stone-wall", {x = -8.5, y = -3.5}, {}},
    {"stone-wall", {x = -8.5, y = -2.5}, {}},
    {"stone-wall", {x = 9.5, y = -3.5}, {}},
    {"stone-wall", {x = -8.5, y = -1.5}, {}},
    {"medium-electric-pole", {x = -6.5, y = -0.5}, {}},
    {"radar", {x = -0.5, y = -0.5}, {}},
    {"radar", {x = 2.5, y = -0.5}, {}},
    {"radar", {x = 5.5, y = -0.5}, {}},
    {"stone-wall", {x = 9.5, y = -0.5}, {}},
    {"stone-wall", {x = 9.5, y = -1.5}, {}},
    {"stone-wall", {x = -8.5, y = 0.5}, {}},
    {"stone-wall", {x = -8.5, y = 1.5}, {}},
    {"medium-electric-pole", {x = 2.5, y = 1.5}, {}},
    {"stone-wall", {x = 9.5, y = 1.5}, {}},
    {"stone-wall", {x = 9.5, y = 0.5}, {}},
    {"stone-wall", {x = -8.5, y = 2.5}, {}},
    {"stone-wall", {x = -8.5, y = 3.5}, {}},
    {"gun-turret", {x = -7, y = 3}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"gun-turret", {x = 8, y = 3}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"stone-wall", {x = 9.5, y = 3.5}, {}},
    {"stone-wall", {x = -8.5, y = 4.5}, {}},
    {"stone-wall", {x = -7.5, y = 4.5}, {}},
    {"stone-wall", {x = -6.5, y = 4.5}, {}},
    {"stone-wall", {x = -5.5, y = 4.5}, {}},
    {"stone-wall", {x = -4.5, y = 4.5}, {}},
    {"stone-wall", {x = -2.5, y = 4.5}, {}},
    {"stone-wall", {x = -1.5, y = 4.5}, {}},
    {"gate", {x = -0.5, y = 4.5}, {dir = "east", }},
    {"gate", {x = 0.5, y = 4.5}, {dir = "east", }},
    {"stone-wall", {x = 3.5, y = 4.5}, {}},
    {"gate", {x = 2.5, y = 4.5}, {dir = "east", }},
    {"stone-wall", {x = 4.5, y = 4.5}, {}},
    {"stone-wall", {x = 5.5, y = 4.5}, {}},
    {"stone-wall", {x = 7.5, y = 4.5}, {}},
    {"stone-wall", {x = 8.5, y = 4.5}, {}},
    {"stone-wall", {x = 9.5, y = 4.5}, {}},
  },
}
