return
{
  entities =
  {
    {"stone-wall", {x = -15.5, y = -15.5}, {}},
    {"stone-wall", {x = -15.5, y = -14.5}, {}},
    {"stone-wall", {x = -14.5, y = -15.5}, {}},
    {"stone-wall", {x = -12.5, y = -15.5}, {}},
    {"stone-wall", {x = -8.5, y = -15.5}, {}},
    {"stone-wall", {x = -9.5, y = -15.5}, {}},
    {"stone-wall", {x = -7.5, y = -15.5}, {}},
    {"stone-wall", {x = -5.5, y = -15.5}, {}},
    {"stone-wall", {x = -2.5, y = -15.5}, {}},
    {"stone-wall", {x = -3.5, y = -15.5}, {}},
    {"stone-wall", {x = -0.5, y = -15.5}, {}},
    {"stone-wall", {x = -1.5, y = -15.5}, {}},
    {"stone-wall", {x = 1.5, y = -15.5}, {}},
    {"stone-wall", {x = 0.5, y = -15.5}, {}},
    {"stone-wall", {x = 2.5, y = -15.5}, {}},
    {"stone-wall", {x = 8.5, y = -15.5}, {}},
    {"stone-wall", {x = 9.5, y = -15.5}, {}},
    {"stone-wall", {x = 11.5, y = -15.5}, {}},
    {"stone-wall", {x = 13.5, y = -15.5}, {}},
    {"stone-wall", {x = 15.5, y = -14.5}, {}},
    {"stone-wall", {x = 15.5, y = -15.5}, {}},
    {"stone-wall", {x = 14.5, y = -15.5}, {}},
    {"stone-wall", {x = -15.5, y = -13.5}, {}},
    {"gun-turret", {x = -12, y = -12}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"fast-inserter", {x = -10.5, y = -12.5}, {dir = "west", }},
    {"transport-belt", {x = -8.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = -7.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = -6.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = -5.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = -4.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = -3.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = -2.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = -1.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = 0.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = 1.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = 2.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = 3.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = 8.5, y = -12.5}, {dir = "east", }},
    {"transport-belt", {x = 9.5, y = -12.5}, {dir = "east", }},
    {"gun-turret", {x = 12, y = -12}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"fast-inserter", {x = 10.5, y = -12.5}, {dir = "west", }},
    {"stone-wall", {x = 15.5, y = -12.5}, {}},
    {"stone-wall", {x = 15.5, y = -13.5}, {}},
    {"stone-wall", {x = -15.5, y = -10.5}, {}},
    {"fast-inserter", {x = -12.5, y = -10.5}, {dir = "south", }},
    {"underground-belt", {x = -10.5, y = -11.5}, {dir = "west", }},
    {"transport-belt", {x = -9.5, y = -11.5}, {dir = "east", }},
    {"transport-belt", {x = -8.5, y = -11.5}, {dir = "east", }},
    {"fast-inserter", {x = -8.5, y = -10.5}, {}},
    {"transport-belt", {x = -7.5, y = -11.5}, {dir = "east", }},
    {"transport-belt", {x = -5.5, y = -11.5}, {dir = "east", }},
    {"transport-belt", {x = -4.5, y = -11.5}, {dir = "east", }},
    {"transport-belt", {x = -2.5, y = -11.5}, {dir = "east", }},
    {"fast-inserter", {x = -3.5, y = -10.5}, {}},
    {"transport-belt", {x = -1.5, y = -11.5}, {dir = "east", }},
    {"medium-electric-pole", {x = 10.5, y = -10.5}, {}},
    {"fast-inserter", {x = 12.5, y = -10.5}, {}},
    {"stone-wall", {x = 15.5, y = -11.5}, {}},
    {"stone-wall", {x = 15.5, y = -10.5}, {}},
    {"stone-wall", {x = -15.5, y = -9.5}, {}},
    {"stone-wall", {x = -15.5, y = -8.5}, {}},
    {"transport-belt", {x = -12.5, y = -9.5}, {}},
    {"transport-belt", {x = -12.5, y = -8.5}, {}},
    {"assembling-machine-2", {x = -7.5, y = -8.5}, {}},
    {"assembling-machine-2", {x = -3.5, y = -8.5}, {}},
    {"transport-belt", {x = 12.5, y = -8.5}, {dir = "south", }},
    {"transport-belt", {x = 12.5, y = -9.5}, {dir = "south", }},
    {"stone-wall", {x = 15.5, y = -8.5}, {}},
    {"transport-belt", {x = -12.5, y = -7.5}, {}},
    {"fast-inserter", {x = -7.5, y = -6.5}, {}},
    {"fast-inserter", {x = -6.5, y = -6.5}, {}},
    {"fast-inserter", {x = -4.5, y = -6.5}, {}},
    {"medium-electric-pole", {x = -5.5, y = -6.5}, {}},
    {"fast-inserter", {x = -3.5, y = -6.5}, {}},
    {"transport-belt", {x = 12.5, y = -6.5}, {dir = "south", }},
    {"transport-belt", {x = 12.5, y = -7.5}, {dir = "south", }},
    {"stone-wall", {x = 15.5, y = -7.5}, {}},
    {"stone-wall", {x = -15.5, y = -4.5}, {}},
    {"stone-wall", {x = -15.5, y = -5.5}, {}},
    {"transport-belt", {x = -12.5, y = -5.5}, {}},
    {"transport-belt", {x = -12.5, y = -4.5}, {}},
    {"assembling-machine-2", {x = -8.5, y = -4.5}, {}},
    {"assembling-machine-2", {x = -5.5, y = -4.5}, {}},
    {"assembling-machine-2", {x = -2.5, y = -4.5}, {}},
    {"transport-belt", {x = 12.5, y = -4.5}, {dir = "south", }},
    {"transport-belt", {x = 12.5, y = -5.5}, {dir = "south", }},
    {"stone-wall", {x = 15.5, y = -4.5}, {}},
    {"stone-wall", {x = 15.5, y = -5.5}, {}},
    {"stone-wall", {x = -15.5, y = -2.5}, {}},
    {"stone-wall", {x = -15.5, y = -3.5}, {}},
    {"transport-belt", {x = -12.5, y = -3.5}, {}},
    {"transport-belt", {x = -12.5, y = -2.5}, {}},
    {"fast-inserter", {x = -6.5, y = -2.5}, {}},
    {"fast-inserter", {x = -7.5, y = -2.5}, {}},
    {"fast-inserter", {x = -4.5, y = -2.5}, {}},
    {"medium-electric-pole", {x = -5.5, y = -2.5}, {}},
    {"fast-inserter", {x = -3.5, y = -2.5}, {}},
    {"transport-belt", {x = 12.5, y = -2.5}, {dir = "south", }},
    {"stone-wall", {x = -15.5, y = -1.5}, {}},
    {"transport-belt", {x = -12.5, y = -1.5}, {}},
    {"transport-belt", {x = -12.5, y = -0.5}, {}},
    {"transport-belt", {x = -9.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -8.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -7.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -6.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -5.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -4.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -3.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -2.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = -1.5, y = -1.5}, {dir = "east", }},
    {"transport-belt", {x = 12.5, y = -1.5}, {dir = "south", }},
    {"stone-wall", {x = 15.5, y = -0.5}, {}},
    {"stone-wall", {x = 15.5, y = -1.5}, {}},
    {"stone-wall", {x = -15.5, y = 0.5}, {}},
    {"stone-wall", {x = -15.5, y = 1.5}, {}},
    {"transport-belt", {x = -12.5, y = 1.5}, {}},
    {"transport-belt", {x = 12.5, y = 1.5}, {dir = "south", }},
    {"stone-wall", {x = 15.5, y = 0.5}, {}},
    {"stone-wall", {x = -15.5, y = 2.5}, {}},
    {"stone-wall", {x = -15.5, y = 3.5}, {}},
    {"transport-belt", {x = -12.5, y = 2.5}, {}},
    {"transport-belt", {x = -12.5, y = 3.5}, {}},
    {"lab", {x = 2.5, y = 4.5}, {}},
    {"transport-belt", {x = 12.5, y = 3.5}, {dir = "south", }},
    {"transport-belt", {x = 12.5, y = 2.5}, {dir = "south", }},
    {"transport-belt", {x = -12.5, y = 5.5}, {}},
    {"transport-belt", {x = 12.5, y = 5.5}, {dir = "south", }},
    {"transport-belt", {x = 12.5, y = 4.5}, {dir = "south", }},
    {"stone-wall", {x = 15.5, y = 4.5}, {}},
    {"stone-wall", {x = 15.5, y = 5.5}, {}},
    {"stone-wall", {x = -15.5, y = 7.5}, {}},
    {"transport-belt", {x = -12.5, y = 7.5}, {}},
    {"lab", {x = 2.5, y = 7.5}, {}},
    {"lab", {x = 5.5, y = 7.5}, {}},
    {"transport-belt", {x = 12.5, y = 7.5}, {dir = "south", }},
    {"stone-wall", {x = -15.5, y = 9.5}, {}},
    {"stone-wall", {x = -15.5, y = 8.5}, {}},
    {"transport-belt", {x = -12.5, y = 8.5}, {}},
    {"transport-belt", {x = -12.5, y = 9.5}, {}},
    {"transport-belt", {x = 12.5, y = 8.5}, {dir = "south", }},
    {"stone-wall", {x = 15.5, y = 9.5}, {}},
    {"transport-belt", {x = -12.5, y = 10.5}, {}},
    {"transport-belt", {x = -11.5, y = 10.5}, {dir = "west", }},
    {"fast-inserter", {x = -11.5, y = 11.5}, {dir = "south", }},
    {"transport-belt", {x = 12.5, y = 10.5}, {dir = "south", }},
    {"fast-inserter", {x = 12.5, y = 11.5}, {}},
    {"stone-wall", {x = 15.5, y = 11.5}, {}},
    {"stone-wall", {x = -15.5, y = 13.5}, {}},
    {"gun-turret", {x = -11, y = 13}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"transport-belt", {x = -7.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = -6.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = -5.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = -4.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = -3.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = -2.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = -1.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = -0.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = 0.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = 5.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = 4.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = 6.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = 7.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = 8.5, y = 13.5}, {dir = "west", }},
    {"transport-belt", {x = 9.5, y = 13.5}, {dir = "west", }},
    {"gun-turret", {x = 12, y = 13}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"fast-inserter", {x = 10.5, y = 13.5}, {dir = "east", }},
    {"stone-wall", {x = 15.5, y = 12.5}, {}},
    {"stone-wall", {x = -15.5, y = 14.5}, {}},
    {"stone-wall", {x = -15.5, y = 15.5}, {}},
    {"stone-wall", {x = -14.5, y = 15.5}, {}},
    {"stone-wall", {x = -13.5, y = 15.5}, {}},
    {"stone-wall", {x = -12.5, y = 15.5}, {}},
    {"stone-wall", {x = -10.5, y = 15.5}, {}},
    {"stone-wall", {x = -9.5, y = 15.5}, {}},
    {"stone-wall", {x = -8.5, y = 15.5}, {}},
    {"stone-wall", {x = -6.5, y = 15.5}, {}},
    {"stone-wall", {x = -4.5, y = 15.5}, {}},
    {"stone-wall", {x = -5.5, y = 15.5}, {}},
    {"stone-wall", {x = -3.5, y = 15.5}, {}},
    {"stone-wall", {x = -0.5, y = 15.5}, {}},
    {"stone-wall", {x = -1.5, y = 15.5}, {}},
    {"stone-wall", {x = 3.5, y = 15.5}, {}},
    {"stone-wall", {x = 5.5, y = 15.5}, {}},
    {"stone-wall", {x = 6.5, y = 15.5}, {}},
    {"stone-wall", {x = 7.5, y = 15.5}, {}},
    {"stone-wall", {x = 9.5, y = 15.5}, {}},
    {"stone-wall", {x = 10.5, y = 15.5}, {}},
    {"stone-wall", {x = 11.5, y = 15.5}, {}},
    {"stone-wall", {x = 14.5, y = 15.5}, {}},
    {"stone-wall", {x = 15.5, y = 15.5}, {}},
    {"stone-wall", {x = 15.5, y = 14.5}, {}},
  },
}
