local m_ruins = {}

table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/assemblingLine"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/carAssembly"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/carBelt"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/centrifuges"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/chemicalPlant"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/crashedShip"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/EFurnace"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/encampment"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/helipad"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/militaryField"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/mountainRange"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/nuclearAccident"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/nuclearPower"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/overgrownFort"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/overwhelmedFlamers"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/overwhelmedGunturrets"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/pipeChain"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/powerSetup"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/radarOutpost"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/roughFort"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/roughPerimeter"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/smallOilSetup"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/smeltery"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/street"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/storageArea"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/swamp"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/trappedRocks"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/treeFortTrapped"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/treeIsland"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/treeRing"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/uraniumMining"))
table.insert(m_ruins, require("__AbandonedRuins__/ruins/mediumRuins/walledSolar"))

return m_ruins
