local m_ruins = {}

table.insert(m_ruins, require("mediumRuins/assemblingLine"))
--table.insert(m_ruins, require("mediumRuins/biterDefense"))
table.insert(m_ruins, require("mediumRuins/chemicalPlant"))
table.insert(m_ruins, require("mediumRuins/centrifuges"))
table.insert(m_ruins, require("mediumRuins/encampment"))
--table.insert(m_ruins, require("mediumRuins/helipad"))
table.insert(m_ruins, require("mediumRuins/militaryField"))
table.insert(m_ruins, require("mediumRuins/mountainRange"))
table.insert(m_ruins, require("mediumRuins/overgrownFort"))
table.insert(m_ruins, require("mediumRuins/pipeChain"))
table.insert(m_ruins, require("mediumRuins/powerSetup"))
--table.insert(m_ruins, require("mediumRuins/queenNest"))
table.insert(m_ruins, require("mediumRuins/radarOutpost"))
--table.insert(m_ruins, require("mediumRuins/railCrossing"))
table.insert(m_ruins, require("mediumRuins/roughFort"))
table.insert(m_ruins, require("mediumRuins/roughPerimeter"))
table.insert(m_ruins, require("mediumRuins/smallOilSetup"))
table.insert(m_ruins, require("mediumRuins/smeltery"))
table.insert(m_ruins, require("mediumRuins/street"))
table.insert(m_ruins, require("mediumRuins/storageArea"))
table.insert(m_ruins, require("mediumRuins/swamp"))
table.insert(m_ruins, require("mediumRuins/treeFortTrapped"))
table.insert(m_ruins, require("mediumRuins/treeIsland"))
table.insert(m_ruins, require("mediumRuins/treeRing"))
table.insert(m_ruins, require("mediumRuins/walledSolar"))

return m_ruins
