return
{
  entities =
  {
    {"stone-wall", {x = -6.5, y = -4.5}, {}},
    {"stone-wall", {x = -6.5, y = -5.5}, {}},
    {"stone-wall", {x = -4.5, y = -5.5}, {}},
    {"stone-wall", {x = -5.5, y = -5.5}, {}},
    {"wooden-chest", {x = -3.5, y = -4.5}, {}},
    {"stone-wall", {x = -2.5, y = -5.5}, {}},
    {"stone-wall", {x = -3.5, y = -5.5}, {}},
    {"gate", {x = -0.5, y = -5.5}, {dir = "east", }},
    {"gate", {x = -1.5, y = -5.5}, {dir = "east", }},
    {"wooden-chest", {x = 0.5, y = -4.5}, {}},
    {"stone-wall", {x = 1.5, y = -5.5}, {}},
    {"stone-wall", {x = 0.5, y = -5.5}, {}},
    {"stone-wall", {x = 3.5, y = -5.5}, {}},
    {"stone-wall", {x = 2.5, y = -5.5}, {}},
    {"stone-wall", {x = 5.5, y = -4.5}, {}},
    {"stone-wall", {x = 5.5, y = -5.5}, {}},
    {"stone-wall", {x = 4.5, y = -5.5}, {}},
    {"stone-wall", {x = -6.5, y = -2.5}, {}},
    {"stone-wall", {x = -6.5, y = -3.5}, {}},
    {"wooden-chest", {x = -4.5, y = -3.5}, {}},
    {"wooden-chest", {x = -5.5, y = -3.5}, {items = {["iron-plate"] = {type= "random", min = 10, max = 200}}, }},
    {"iron-chest", {x = -0.5, y = -2.5}, {}},
    {"wooden-chest", {x = 1.5, y = -2.5}, {}},
    {"wooden-chest", {x = 1.5, y = -3.5}, {items = {["copper-plate"] = {type= "random", min = 10, max = 200}}, }},
    {"iron-chest", {x = 3.5, y = -2.5}, {items = {["transport-belt"] = {type= "random", min = 10, max = 70}}, }},
    {"wooden-chest", {x = 2.5, y = -3.5}, {}},
    {"stone-wall", {x = 5.5, y = -2.5}, {}},
    {"stone-wall", {x = 5.5, y = -3.5}, {}},
    {"gate", {x = -6.5, y = -0.5}, {}},
    {"stone-wall", {x = -6.5, y = -1.5}, {}},
    {"iron-chest", {x = -5.5, y = -0.5}, {items = {["iron-plate"] = {type= "random", min = 10, max = 200}}, }},
    {"wooden-chest", {x = -3.5, y = -1.5}, {items = {["steel-plate"] = {type= "random", min = 10, max = 200}}, }},
    {"wooden-chest", {x = -0.5, y = -0.5}, {}},
    {"iron-chest", {x = 3.5, y = -1.5}, {}},
    {"gate", {x = 5.5, y = -0.5}, {}},
    {"gate", {x = 5.5, y = -1.5}, {}},
    {"stone-wall", {x = -6.5, y = 1.5}, {}},
    {"gate", {x = -6.5, y = 0.5}, {}},
    {"wooden-chest", {x = -4.5, y = 0.5}, {}},
    {"iron-chest", {x = -2.5, y = 1.5}, {}},
    {"wooden-chest", {x = -2.5, y = 0.5}, {items = {["iron-ore"] = {type= "random", min = 50, max = 200}}, }},
    {"wooden-chest", {x = 1.5, y = 1.5}, {}},
    {"wooden-chest", {x = 0.5, y = 1.5}, {items = {stone = {type= "random", min = 10, max = 200}}, }},
    {"iron-chest", {x = 3.5, y = 0.5}, {}},
    {"stone-wall", {x = 5.5, y = 1.5}, {}},
    {"stone-wall", {x = 5.5, y = 0.5}, {}},
    {"stone-wall", {x = -6.5, y = 3.5}, {}},
    {"stone-wall", {x = -6.5, y = 2.5}, {}},
    {"wooden-chest", {x = -4.5, y = 2.5}, {}},
    {"wooden-chest", {x = -5.5, y = 2.5}, {items = {coal = {type= "random", min = 10, max = 200}}, }},
    {"wooden-chest", {x = -2.5, y = 3.5}, {items = {["repair-pack"] = {type= "random", min = 10, max = 20}}, }},
    {"wooden-chest", {x = -3.5, y = 2.5}, {}},
    {"wooden-chest", {x = -1.5, y = 3.5}, {}},
    {"wooden-chest", {x = 1.5, y = 2.5}, {}},
    {"wooden-chest", {x = 3.5, y = 2.5}, {items = {inserter = {type= "random", min = 10, max = 20}}, }},
    {"stone-wall", {x = 5.5, y = 3.5}, {}},
    {"stone-wall", {x = 5.5, y = 2.5}, {}},
    {"stone-wall", {x = -6.5, y = 5.5}, {}},
    {"stone-wall", {x = -6.5, y = 4.5}, {}},
    {"wooden-chest", {x = -5.5, y = 4.5}, {items = {["copper-plate"] = {type= "random", min = 10, max = 200}}, }},
    {"iron-chest", {x = -3.5, y = 4.5}, {}},
    {"iron-chest", {x = -0.5, y = 4.5}, {}},
    {"iron-chest", {x = 2.5, y = 4.5}, {items = {["gun-turret"] = {type= "random", min = 10, max = 20}}, }},
    {"stone-wall", {x = 5.5, y = 5.5}, {}},
    {"stone-wall", {x = 5.5, y = 4.5}, {}},
    {"stone-wall", {x = -6.5, y = 6.5}, {}},
    {"stone-wall", {x = -4.5, y = 6.5}, {}},
    {"stone-wall", {x = -5.5, y = 6.5}, {}},
    {"stone-wall", {x = -2.5, y = 6.5}, {}},
    {"stone-wall", {x = -3.5, y = 6.5}, {}},
    {"gate", {x = -0.5, y = 6.5}, {dir = "east", }},
    {"stone-wall", {x = -1.5, y = 6.5}, {}},
    {"stone-wall", {x = 1.5, y = 6.5}, {}},
    {"gate", {x = 0.5, y = 6.5}, {dir = "east", }},
    {"stone-wall", {x = 3.5, y = 6.5}, {}},
    {"stone-wall", {x = 2.5, y = 6.5}, {}},
    {"stone-wall", {x = 5.5, y = 6.5}, {}},
    {"stone-wall", {x = 4.5, y = 6.5}, {}},
  },
}
