return
{
  entities =
  {
    {"medium-electric-pole", {x = 3.5, y = -5.5}, {}},
    {"medium-electric-pole", {x = -0.5, y = -2.5}, {}},
    {"steam-engine", {x = -3.5, y = 0.5}, {}},
    {"steam-engine", {x = -0.5, y = 0.5}, {}},
    {"steam-engine", {x = 2.5, y = 0.5}, {}},
    {"steam-engine-remnants", {x = 5.5, y = 0.5}, {}},
    {"medium-electric-pole-remnants", {x = 7.5, y = 0.5}, {}},
    {"medium-electric-pole-remnants", {x = -6.5, y = 2.5}, {}},
    {"boiler", {x = -3.5, y = 4}, {}},
    {"boiler", {x = 2.5, y = 4}, {}},
    {"burner-inserter", {x = -3.5, y = 5.5}, {dir = "south", }},
    {"boiler-remnants", {x = -0.5, y = 4}, {}},
    {"burner-inserter", {x = -0.5, y = 5.5}, {dir = "south", }},
    {"burner-inserter", {x = 2.5, y = 5.5}, {dir = "south", }},
    {"boiler-remnants", {x = 5.5, y = 4}, {}},
    {"burner-inserter-remnants", {x = 6.5, y = 5.5}, {dir = "south", }},
    {"transport-belt-remnants", {x = -6.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = -7.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = -5.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -4.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -2.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -3.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = -1.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -0.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = 1.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = 0.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 3.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = 2.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 4.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 5.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 6.5, y = 6.5}, {dir = "east", }},
  },
  tiles =
  {
    {"grass-1", {x = -8, y = -8}},
    {"grass-1", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"grass-1", {x = -8, y = -1}},
    {"grass-1", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"grass-1", {x = -7, y = -1}},
    {"grass-1", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-1", {x = -4, y = -7}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"grass-1", {x = -4, y = 7}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-1", {x = -3, y = 7}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-1", {x = -2, y = -7}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-1", {x = 0, y = -7}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-1", {x = 1, y = -7}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 4, y = 6}},
    {"grass-1", {x = 4, y = 7}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-1", {x = 5, y = 7}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-1", {x = 6, y = 7}},
    {"grass-1", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-1", {x = 7, y = 6}},
    {"grass-1", {x = 7, y = 7}},
  }
}
