return
{
  entities =
  {
    {"stone-wall", {x = -5.5, y = -2.5}, {}},
    {"stone-wall", {x = -4.5, y = -2.5}, {}},
    {"stone-wall", {x = -2.5, y = -2.5}, {}},
    {"stone-wall", {x = -3.5, y = -2.5}, {}},
    {"stone-wall", {x = -1.5, y = -2.5}, {}},
    {"stone-wall", {x = -0.5, y = -2.5}, {}},
    {"stone-wall", {x = 0.5, y = -2.5}, {}},
    {"stone-wall", {x = 1.5, y = -2.5}, {}},
    {"stone-wall", {x = -5.5, y = -0.5}, {}},
    {"stone-wall", {x = -5.5, y = -1.5}, {}},
    {"radar", {x = 0.5, y = 0.5}, {}},
    {"stone-wall", {x = 1.5, y = -1.5}, {}},
    {"stone-wall", {x = 2.5, y = -1.5}, {}},
    {"stone-wall", {x = 3.5, y = -1.5}, {}},
    {"stone-wall", {x = 4.5, y = -1.5}, {}},
    {"gate", {x = 4.5, y = -0.5}, {}},
    {"stone-wall", {x = -5.5, y = 1.5}, {}},
    {"stone-wall", {x = -5.5, y = 0.5}, {}},
    {"gun-turret", {x = -3, y = 1}, {force = "enemy", items = {["firearm-magazine"] = 5}, }},
    {"medium-electric-pole", {x = -1.5, y = 0.5}, {}},
    {"stone-wall", {x = 4.5, y = 1.5}, {}},
    {"gate", {x = 4.5, y = 0.5}, {}},
    {"stone-wall", {x = -5.5, y = 3.5}, {}},
    {"stone-wall", {x = -5.5, y = 2.5}, {}},
    {"stone-wall", {x = -4.5, y = 3.5}, {}},
    {"stone-wall", {x = -2.5, y = 3.5}, {}},
    {"stone-wall", {x = -3.5, y = 3.5}, {}},
    {"stone-wall", {x = -0.5, y = 3.5}, {}},
    {"stone-wall", {x = -1.5, y = 3.5}, {}},
    {"stone-wall", {x = 1.5, y = 3.5}, {}},
    {"stone-wall", {x = 0.5, y = 3.5}, {}},
    {"stone-wall", {x = 3.5, y = 2.5}, {}},
    {"stone-wall", {x = 3.5, y = 3.5}, {}},
    {"stone-wall", {x = 2.5, y = 3.5}, {}},
    {"stone-wall", {x = 4.5, y = 2.5}, {}},
    {"medium-electric-pole", {x = 4.5, y = 3.5}, {}},
  },
}
