return
{
  entities =
  {
    {"lab", {x = -6.5, y = -9.5}, {}},
    {"fast-inserter", {x = -4.5, y = -10.5}, {dir = "west", }},
    {"lab", {x = -2.5, y = -9.5}, {}},
    {"lab", {x = 1.5, y = -9.5}, {}},
    {"fast-inserter", {x = 3.5, y = -10.5}, {dir = "west", }},
    {"small-electric-pole", {x = -4.5, y = -9.5}, {}},
    {"fast-inserter", {x = -0.5, y = -8.5}, {dir = "west", }},
    {"fast-inserter", {x = 3.5, y = -8.5}, {dir = "west", }},
    {"small-electric-pole", {x = 3.5, y = -9.5}, {}},
    {"lab", {x = -6.5, y = -5.5}, {}},
    {"fast-inserter", {x = -4.5, y = -6.5}, {dir = "east", }},
    {"lab", {x = -2.5, y = -5.5}, {}},
    {"lab", {x = 1.5, y = -5.5}, {}},
    {"fast-inserter", {x = 3.5, y = -6.5}, {dir = "east", }},
    {"lab", {x = 5.5, y = -5.5}, {}},
    {"small-electric-pole", {x = 5.5, y = -7.5}, {}},
    {"fast-inserter", {x = 4.5, y = -7.5}, {}},
    {"fast-inserter", {x = 6.5, y = -7.5}, {}},
    {"small-electric-pole", {x = -4.5, y = -5.5}, {}},
    {"small-electric-pole", {x = -0.5, y = -5.5}, {}},
    {"fast-inserter", {x = 3.5, y = -4.5}, {dir = "east", }},
    {"small-electric-pole", {x = 3.5, y = -5.5}, {}},
    {"radar", {x = 7.5, y = 0.5}, {}},
    {"stone-furnace", {x = -1, y = 2}, {}},
    {"transport-belt", {x = -6.5, y = 2.5}, {dir = "east", }},
    {"transport-belt", {x = -4.5, y = 2.5}, {dir = "east", }},
    {"transport-belt", {x = -3.5, y = 3.5}, {dir = "south", }},
    {"transport-belt", {x = -3.5, y = 2.5}, {dir = "south", }},
    {"stone-furnace", {x = -1, y = 4}, {}},
    {"transport-belt", {x = 1.5, y = 3.5}, {dir = "south", }},
    {"fast-inserter", {x = 0.5, y = 2.5}, {dir = "west", }},
    {"fast-inserter", {x = -2.5, y = 4.5}, {dir = "west", }},
    {"transport-belt", {x = -3.5, y = 4.5}, {dir = "south", }},
    {"stone-furnace", {x = -1, y = 6}, {}},
    {"transport-belt", {x = 1.5, y = 5.5}, {dir = "south", }},
    {"transport-belt", {x = 1.5, y = 4.5}, {dir = "south", }},
    {"fast-inserter", {x = 0.5, y = 4.5}, {dir = "west", }},
    {"transport-belt", {x = -3.5, y = 7.5}, {dir = "south", }},
    {"fast-inserter", {x = -2.5, y = 6.5}, {dir = "west", }},
    {"transport-belt", {x = -3.5, y = 6.5}, {dir = "south", }},
    {"stone-furnace", {x = -1, y = 8}, {}},
    {"transport-belt", {x = 1.5, y = 7.5}, {dir = "south", }},
    {"transport-belt", {x = -3.5, y = 8.5}, {dir = "south", }},
    {"stone-furnace", {x = -1, y = 10}, {}},
    {"transport-belt", {x = 1.5, y = 9.5}, {dir = "south", }},
    {"transport-belt", {x = 1.5, y = 8.5}, {dir = "south", }},
    {"fast-inserter", {x = 0.5, y = 8.5}, {dir = "west", }},
    {"fast-inserter", {x = -2.5, y = 10.5}, {dir = "west", }},
    {"transport-belt", {x = -3.5, y = 10.5}, {dir = "south", }},
  },
}
