
return function(center) --orchard
    local randomTree = "tree-0" .. tostring(math.random(1,9))
    local ce = game.surfaces[1].create_entity --save typing
    local fN = game.forces.neutral

    ce{name = randomTree, position = {center.x+(-12.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-10.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-8.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-6.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-4.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-2.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-0.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(1.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(3.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(5.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(7.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(9.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(11.5),center.y+(-12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-12.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-10.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-8.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-6.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-4.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-2.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-0.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(1.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(3.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(5.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(7.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(9.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(11.5),center.y+(-7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-12.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-10.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-8.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-6.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-4.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-2.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-0.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(1.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(3.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(5.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(7.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(9.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(11.5),center.y+(-2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-12.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-10.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-8.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-6.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-4.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-2.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-0.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(1.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(3.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(5.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(7.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(9.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(11.5),center.y+(2.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-12.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-10.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-8.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-6.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-4.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-2.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-0.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(1.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(3.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(5.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(7.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(9.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(11.5),center.y+(7.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-12.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-10.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-8.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-6.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-4.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-2.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(-0.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(1.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(3.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(5.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(7.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(9.5),center.y+(12.5)}, force = fN}
    ce{name = randomTree, position = {center.x+(11.5),center.y+(12.5)}, force = fN}
end
