return
{
  entities =
  {
    {"stone-wall", {x = -13.5, y = -14.5}, {}},
    {"stone-wall", {x = -12.5, y = -14.5}, {}},
    {"stone-wall", {x = -10.5, y = -14.5}, {}},
    {"stone-wall", {x = -11.5, y = -14.5}, {}},
    {"stone-wall", {x = -8.5, y = -14.5}, {}},
    {"stone-wall", {x = -9.5, y = -14.5}, {}},
    {"stone-wall", {x = -2.5, y = -14.5}, {}},
    {"stone-wall", {x = -3.5, y = -14.5}, {}},
    {"stone-wall", {x = -0.5, y = -14.5}, {}},
    {"stone-wall", {x = -1.5, y = -14.5}, {}},
    {"stone-wall", {x = 1.5, y = -14.5}, {}},
    {"stone-wall", {x = 0.5, y = -14.5}, {}},
    {"stone-wall", {x = 3.5, y = -14.5}, {}},
    {"stone-wall", {x = 2.5, y = -14.5}, {}},
    {"stone-wall", {x = 5.5, y = -14.5}, {}},
    {"stone-wall", {x = 9.5, y = -14.5}, {}},
    {"stone-wall", {x = 11.5, y = -14.5}, {}},
    {"stone-wall", {x = 10.5, y = -14.5}, {}},
    {"stone-wall", {x = 13.5, y = -14.5}, {}},
    {"stone-wall", {x = 12.5, y = -14.5}, {}},
    {"stone-wall", {x = 14.5, y = -14.5}, {}},
    {"stone-wall", {x = -13.5, y = -13.5}, {}},
    {"stone-wall", {x = -13.5, y = -12.5}, {}},
    {"stone-wall", {x = -2.5, y = -13.5}, {}},
    {"stone-wall", {x = -3.5, y = -12.5}, {}},
    {"stone-wall", {x = -2.5, y = -12.5}, {}},
    {"stone-wall", {x = -13.5, y = -11.5}, {}},
    {"stone-wall", {x = -13.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -11.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -9.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -7.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -5.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -3.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -1.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 0.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 2.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 4.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 6.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 8.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 10.5, y = -10.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 12.5, y = -10.5}, {}},
    {"stone-wall", {x = 14.5, y = -10.5}, {}},
    {"stone-wall", {x = 14.5, y = -11.5}, {}},
    {"stone-wall", {x = -13.5, y = -9.5}, {}},
    {"stone-wall", {x = -13.5, y = -8.5}, {}},
    {"stone-wall", {x = -13.5, y = -7.5}, {}},
    {"stone-wall", {x = -13.5, y = -6.5}, {}},
    {"stone-wall", {x = -12.5, y = -6.5}, {}},
    {"stone-wall", {x = -11.5, y = -6.5}, {}},
    {"stone-wall", {x = 14.5, y = -6.5}, {}},
    {"stone-wall", {x = -13.5, y = -5.5}, {}},
    {"stone-wall", {x = -13.5, y = -4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -11.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -9.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -7.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -5.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -3.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -1.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 0.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 2.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 4.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 6.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 8.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 10.5, y = -5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 12.5, y = -5.5}, {}},
    {"stone-wall", {x = 14.5, y = -4.5}, {}},
    {"stone-wall", {x = 14.5, y = -5.5}, {}},
    {"stone-wall", {x = -13.5, y = -3.5}, {}},
    {"stone-wall", {x = -13.5, y = -2.5}, {}},
    {"stone-wall", {x = 14.5, y = -3.5}, {}},
    {"stone-wall", {x = -13.5, y = -1.5}, {}},
    {"stone-wall", {x = -13.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -11.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -9.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -7.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -5.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -3.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -1.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 0.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 2.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 4.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 6.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 8.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 10.5, y = -0.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 12.5, y = -0.5}, {}},
    {"stone-wall", {x = 14.5, y = -0.5}, {}},
    {"stone-wall", {x = 14.5, y = -1.5}, {}},
    {"stone-wall", {x = -13.5, y = 0.5}, {}},
    {"stone-wall", {x = 14.5, y = 1.5}, {}},
    {"stone-wall", {x = 14.5, y = 0.5}, {}},
    {"stone-wall", {x = -14.5, y = 3.5}, {}},
    {"stone-wall", {x = 14.5, y = 2.5}, {}},
    {"stone-wall", {x = -14.5, y = 4.5}, {}},
    {"stone-wall", {x = -14.5, y = 5.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -11.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -9.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -7.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -5.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -3.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -1.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 0.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 2.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 4.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 6.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 8.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 10.5, y = 4.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 12.5, y = 4.5}, {}},
    {"stone-wall", {x = 14.5, y = 4.5}, {}},
    {"stone-wall", {x = -14.5, y = 6.5}, {}},
    {"stone-wall", {x = 14.5, y = 7.5}, {}},
    {"stone-wall", {x = 14.5, y = 6.5}, {}},
    {"stone-wall", {x = -13.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -11.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -9.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -7.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -5.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -3.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = -1.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 0.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 2.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 4.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 6.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 8.5, y = 9.5}, {}},
    {{type = "random-of-entity-type", entity_type = "tree"}, {x = 10.5, y = 9.5}, {}},
    {"stone-wall", {x = 14.5, y = 9.5}, {}},
    {"stone-wall", {x = 14.5, y = 8.5}, {}},
    {"stone-wall", {x = -13.5, y = 10.5}, {}},
    {"stone-wall", {x = -13.5, y = 11.5}, {}},
    {"stone-wall", {x = 13.5, y = 11.5}, {}},
    {"stone-wall", {x = 14.5, y = 10.5}, {}},
    {"stone-wall", {x = -13.5, y = 12.5}, {}},
    {"stone-wall", {x = -13.5, y = 13.5}, {}},
    {"stone-wall", {x = -0.5, y = 13.5}, {}},
    {"stone-wall", {x = 1.5, y = 13.5}, {}},
    {"stone-wall", {x = 11.5, y = 13.5}, {}},
    {"stone-wall", {x = 12.5, y = 13.5}, {}},
    {"stone-wall", {x = 13.5, y = 13.5}, {}},
    {"stone-wall", {x = 14.5, y = 13.5}, {}},
    {"stone-wall", {x = -13.5, y = 14.5}, {}},
    {"stone-wall", {x = -12.5, y = 14.5}, {}},
    {"stone-wall", {x = -11.5, y = 14.5}, {}},
    {"stone-wall", {x = -10.5, y = 14.5}, {}},
    {"stone-wall", {x = -9.5, y = 14.5}, {}},
    {"stone-wall", {x = -8.5, y = 14.5}, {}},
    {"stone-wall", {x = -7.5, y = 14.5}, {}},
    {"stone-wall", {x = -6.5, y = 14.5}, {}},
    {"stone-wall", {x = -5.5, y = 14.5}, {}},
    {"stone-wall", {x = -4.5, y = 14.5}, {}},
    {"stone-wall", {x = -3.5, y = 14.5}, {}},
    {"stone-wall", {x = -2.5, y = 14.5}, {}},
    {"stone-wall", {x = -1.5, y = 14.5}, {}},
    {"stone-wall", {x = -0.5, y = 14.5}, {}},
    {"stone-wall", {x = 0.5, y = 14.5}, {}},
    {"stone-wall", {x = 1.5, y = 14.5}, {}},
    {"stone-wall", {x = 2.5, y = 14.5}, {}},
    {"stone-wall", {x = 4.5, y = 14.5}, {}},
    {"stone-wall", {x = 5.5, y = 14.5}, {}},
    {"stone-wall", {x = 6.5, y = 14.5}, {}},
    {"stone-wall", {x = 7.5, y = 14.5}, {}},
  },
}
